# -*- coding: utf-8 -*-
from typing import List, Tuple

__all__ = [
    "Jieba",
    "cut",
    "cut_all",
    "cut_for_search",
    "tag",
    "tokenize",
]

class Jieba:
    def __init__(self) -> None: ...
    def cut(self, text: str, hmm: bool = True) -> List[str]: ...
    def cut_all(self, text: str) -> List[str]: ...
    def cut_for_search(self, text: str, hmm: bool = True) -> List[str]: ...
    def tag(self, text: str, hmm: bool = True) -> List[Tuple[str, str]]: ...
    def tokenize(
        self, text: str, mode: str = "default", hmm: bool = True
    ) -> List[Tuple[str, int, int]]: ...

_DEFAULT_JIEBA: Jieba

def cut(text: str, hmm: bool = True) -> List[str]: ...
def cut_all(text: str) -> List[str]: ...
def cut_for_search(text: str, hmm: bool = True) -> List[str]: ...
def tag(text: str, hmm: bool = True) -> List[Tuple[str, str]]: ...
def tokenize(
    text: str, mode: str = "default", hmm: bool = True
) -> List[Tuple[str, int, int]]: ...
